version: "3.9"
name: assistant-ai-bot-test

networks:
  assistant_network:
    driver: bridge

services:
  postgres:
    restart: always
    image: postgres:15.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=assistant
    volumes:
      - postgres:/data/postgres
    ports:
      - "15432:5432"
    networks:
      - assistant_network

volumes:
  postgres: